# Generated by Django 4.1.7 on 2023-02-26 09:30

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfile', models.FileField(upload_to=files.models.file_upload_path)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
