# Generated by Django 4.1.7 on 2023-02-28 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('done', models.BooleanField(default=False)),
                ('tiemstamp', models.DateTimeField(default=datetime.datetime(2023, 2, 28, 22, 0, 21, 787991, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
